name: Build and Push Docker Image to Aliyun ACR-420

on:
  push:
    branches:
      - main
    # tags:
    #   - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 必须加，你的项目需要子模块

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录阿里云容器镜像服务（已按你要求修改）
      - name: Login to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      # 构建并推送镜像
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.ALIYUN_REGISTRY }}/ktransformers:latest
            ${{ secrets.ALIYUN_REGISTRY }}/ktransformers:${{ github.sha }}
